# fish completion for sentry
# Auto-generated from command definitions

# Disable file completion by default
complete -c sentry -f

# Dynamic completion for positional values
function __sentry_complete_dynamic
  # commandline -opc: all tokens before cursor (excludes current partial)
  # commandline -ct: the current token being completed (the partial)
  set -l preceding (commandline -opc)
  set -l current (commandline -ct)
  # Quote $current so an empty partial (TAB after space) is passed as ""
  # instead of being silently dropped by fish's empty-list expansion.
  sentry __complete $preceding[2..] "$current" 2>/dev/null | while read -l line
    echo $line
  end
end

# Top-level commands
complete -c sentry -n "__fish_use_subcommand" -a "auth" -d "Authenticate with Sentry"
complete -c sentry -n "__fish_use_subcommand" -a "cli" -d "CLI-related commands"
complete -c sentry -n "__fish_use_subcommand" -a "dashboard" -d "Manage Sentry dashboards"
complete -c sentry -n "__fish_use_subcommand" -a "org" -d "Work with Sentry organizations"
complete -c sentry -n "__fish_use_subcommand" -a "project" -d "Work with Sentry projects"
complete -c sentry -n "__fish_use_subcommand" -a "repo" -d "Work with Sentry repositories"
complete -c sentry -n "__fish_use_subcommand" -a "team" -d "Work with Sentry teams"
complete -c sentry -n "__fish_use_subcommand" -a "issue" -d "Manage Sentry issues"
complete -c sentry -n "__fish_use_subcommand" -a "event" -d "View Sentry events"
complete -c sentry -n "__fish_use_subcommand" -a "log" -d "View Sentry logs"
complete -c sentry -n "__fish_use_subcommand" -a "sourcemap" -d "Manage sourcemaps"
complete -c sentry -n "__fish_use_subcommand" -a "span" -d "List and view spans in projects or traces"
complete -c sentry -n "__fish_use_subcommand" -a "trace" -d "View distributed traces"
complete -c sentry -n "__fish_use_subcommand" -a "trial" -d "Manage product trials"
complete -c sentry -n "__fish_use_subcommand" -a "help" -d "Display help for a command"
complete -c sentry -n "__fish_use_subcommand" -a "init" -d "Initialize Sentry in your project \(experimental\)"
complete -c sentry -n "__fish_use_subcommand" -a "api" -d "Make an authenticated API request"
complete -c sentry -n "__fish_use_subcommand" -a "schema" -d "Browse the Sentry API schema"

# auth subcommands
complete -c sentry -n "__fish_seen_subcommand_from auth" -a "login" -d "Authenticate with Sentry"
complete -c sentry -n "__fish_seen_subcommand_from auth" -a "logout" -d "Log out of Sentry"
complete -c sentry -n "__fish_seen_subcommand_from auth" -a "refresh" -d "Refresh your authentication token"
complete -c sentry -n "__fish_seen_subcommand_from auth" -a "status" -d "View authentication status"
complete -c sentry -n "__fish_seen_subcommand_from auth" -a "token" -d "Print the stored authentication token"
complete -c sentry -n "__fish_seen_subcommand_from auth" -a "whoami" -d "Show the currently authenticated user"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from login" -l "token" -d "Authenticate using an API token instead of OAuth"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from login" -l "timeout" -d "Timeout for OAuth flow in seconds \(default: 900\)"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from login" -l "force" -d "Re-authenticate without prompting"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from login" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from login" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from logout" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from logout" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from refresh" -l "force" -d "Force refresh even if token is still valid"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from refresh" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from refresh" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from status" -l "show-token" -d "Show the stored token \(masked by default\)"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from status" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from status" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from status" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from token" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from token" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from whoami" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from whoami" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from auth; and __fish_seen_subcommand_from whoami" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"

# cli subcommands
complete -c sentry -n "__fish_seen_subcommand_from cli" -a "feedback" -d "Send feedback about the CLI"
complete -c sentry -n "__fish_seen_subcommand_from cli" -a "fix" -d "Diagnose and repair CLI database issues"
complete -c sentry -n "__fish_seen_subcommand_from cli" -a "setup" -d "Configure shell integration"
complete -c sentry -n "__fish_seen_subcommand_from cli" -a "upgrade" -d "Update the Sentry CLI to the latest version"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from feedback" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from feedback" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from fix" -l "dry-run" -d "Show what would be fixed without making changes"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from fix" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from fix" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from setup" -l "install" -d "Install the binary from a temp location to the system path"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from setup" -l "method" -d "Installation method \(curl, npm, pnpm, bun, yarn\)"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from setup" -l "channel" -d "Release channel to persist \(stable or nightly\)"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from setup" -l "no-modify-path" -d "Skip PATH modification"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from setup" -l "no-completions" -d "Skip shell completion installation"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from setup" -l "no-agent-skills" -d "Skip agent skill installation for AI coding assistants"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from setup" -l "quiet" -d "Suppress output \(for scripted usage\)"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from setup" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from setup" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from upgrade" -l "check" -d "Check for updates without installing"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from upgrade" -l "force" -d "Force upgrade even if already on the latest version"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from upgrade" -l "offline" -d "Upgrade using only cached version info and patches \(no network\)"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from upgrade" -l "method" -d "Installation method to use \(curl, brew, npm, pnpm, bun, yarn\)"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from upgrade" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from cli; and __fish_seen_subcommand_from upgrade" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"

# dashboard subcommands
complete -c sentry -n "__fish_seen_subcommand_from dashboard" -a "list" -d "List dashboards"
complete -c sentry -n "__fish_seen_subcommand_from dashboard" -a "view" -d "View a dashboard"
complete -c sentry -n "__fish_seen_subcommand_from dashboard" -a "create" -d "Create a dashboard"
complete -c sentry -n "__fish_seen_subcommand_from dashboard" -a "widget" -d "Manage dashboard widgets"
complete -c sentry -n "__fish_seen_subcommand_from dashboard; and __fish_seen_subcommand_from list" -l "web" -d "Open in browser"
complete -c sentry -n "__fish_seen_subcommand_from dashboard; and __fish_seen_subcommand_from list" -l "limit" -d "Maximum number of dashboards to list"
complete -c sentry -n "__fish_seen_subcommand_from dashboard; and __fish_seen_subcommand_from list" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from dashboard; and __fish_seen_subcommand_from list" -l "cursor" -d "Navigate pages: \"next\", \"prev\", \"first\" \(or raw cursor string\)"
complete -c sentry -n "__fish_seen_subcommand_from dashboard; and __fish_seen_subcommand_from list" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from dashboard; and __fish_seen_subcommand_from list" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from dashboard; and __fish_seen_subcommand_from view" -l "web" -d "Open in browser"
complete -c sentry -n "__fish_seen_subcommand_from dashboard; and __fish_seen_subcommand_from view" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from dashboard; and __fish_seen_subcommand_from view" -l "refresh" -d "Auto-refresh interval in seconds \(default: 60, min: 10\)"
complete -c sentry -n "__fish_seen_subcommand_from dashboard; and __fish_seen_subcommand_from view" -l "period" -d "Time period override \(e.g., \"24h\", \"7d\", \"14d\"\)"
complete -c sentry -n "__fish_seen_subcommand_from dashboard; and __fish_seen_subcommand_from view" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from dashboard; and __fish_seen_subcommand_from view" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from dashboard; and __fish_seen_subcommand_from create" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from dashboard; and __fish_seen_subcommand_from create" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"

# org subcommands
complete -c sentry -n "__fish_seen_subcommand_from org" -a "list" -d "List organizations"
complete -c sentry -n "__fish_seen_subcommand_from org" -a "view" -d "View details of an organization"
complete -c sentry -n "__fish_seen_subcommand_from org; and __fish_seen_subcommand_from list" -l "limit" -d "Maximum number of organizations to list"
complete -c sentry -n "__fish_seen_subcommand_from org; and __fish_seen_subcommand_from list" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from org; and __fish_seen_subcommand_from list" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from org; and __fish_seen_subcommand_from list" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from org; and __fish_seen_subcommand_from view" -l "web" -d "Open in browser"
complete -c sentry -n "__fish_seen_subcommand_from org; and __fish_seen_subcommand_from view" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from org; and __fish_seen_subcommand_from view" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from org; and __fish_seen_subcommand_from view" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"

# project subcommands
complete -c sentry -n "__fish_seen_subcommand_from project" -a "create" -d "Create a new project"
complete -c sentry -n "__fish_seen_subcommand_from project" -a "delete" -d "Delete a project"
complete -c sentry -n "__fish_seen_subcommand_from project" -a "list" -d "List projects"
complete -c sentry -n "__fish_seen_subcommand_from project" -a "view" -d "View details of a project"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from create" -l "team" -d "Team to create the project under"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from create" -l "dry-run" -d "Validate inputs and show what would be created without creating it"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from create" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from create" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete" -l "yes" -d "Skip confirmation prompt"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete" -l "force" -d "Force deletion without confirmation"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete" -l "dry-run" -d "Validate and show what would be deleted without deleting"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list" -l "limit" -d "Maximum number of projects to list"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list" -l "platform" -d "Filter by platform \(e.g., javascript, python\)"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list" -l "cursor" -d "Navigate pages: \"next\", \"prev\", \"first\" \(or raw cursor string\)"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from view" -l "web" -d "Open in browser"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from view" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from view" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from view" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"

# repo subcommands
complete -c sentry -n "__fish_seen_subcommand_from repo" -a "list" -d "List repositories"
complete -c sentry -n "__fish_seen_subcommand_from repo; and __fish_seen_subcommand_from list" -l "limit" -d "Maximum number of repositories to list"
complete -c sentry -n "__fish_seen_subcommand_from repo; and __fish_seen_subcommand_from list" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from repo; and __fish_seen_subcommand_from list" -l "cursor" -d "Navigate pages: \"next\", \"prev\", \"first\" \(or raw cursor string\)"
complete -c sentry -n "__fish_seen_subcommand_from repo; and __fish_seen_subcommand_from list" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from repo; and __fish_seen_subcommand_from list" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\). Available: id, name, url, provider, status, dateCreated, integrationId, externalSlug, externalId"

# team subcommands
complete -c sentry -n "__fish_seen_subcommand_from team" -a "list" -d "List teams"
complete -c sentry -n "__fish_seen_subcommand_from team; and __fish_seen_subcommand_from list" -l "limit" -d "Maximum number of teams to list"
complete -c sentry -n "__fish_seen_subcommand_from team; and __fish_seen_subcommand_from list" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from team; and __fish_seen_subcommand_from list" -l "cursor" -d "Navigate pages: \"next\", \"prev\", \"first\" \(or raw cursor string\)"
complete -c sentry -n "__fish_seen_subcommand_from team; and __fish_seen_subcommand_from list" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from team; and __fish_seen_subcommand_from list" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\). Available: id, slug, name, dateCreated, isMember, teamRole, memberCount"

# issue subcommands
complete -c sentry -n "__fish_seen_subcommand_from issue" -a "list" -d "List issues in a project"
complete -c sentry -n "__fish_seen_subcommand_from issue" -a "explain" -d "Analyze an issue's root cause using Seer AI"
complete -c sentry -n "__fish_seen_subcommand_from issue" -a "plan" -d "Generate a solution plan using Seer AI"
complete -c sentry -n "__fish_seen_subcommand_from issue" -a "view" -d "View details of a specific issue"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from list" -l "query" -d "Search query \(Sentry search syntax\)"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from list" -l "limit" -d "Maximum number of issues to list"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from list" -l "sort" -d "Sort by: date, new, freq, user"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from list" -l "period" -d "Time period for issue activity \(e.g. 24h, 14d, 90d\)"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from list" -l "cursor" -d "Pagination cursor \(use \"next\" for next page, \"prev\" for previous\)"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from list" -l "compact" -d "Single-line rows for compact output \(auto-detects if omitted\)"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from list" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from list" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from list" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\). Available: id, shortId, title, culprit, count, userCount, firstSeen, lastSeen, level, status, priority, platform, permalink, project, metadata, assignedTo, substatus, isUnhandled, seerFixabilityScore"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from explain" -l "force" -d "Force new analysis even if one exists"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from explain" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from explain" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from explain" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from plan" -l "cause" -d "Root cause ID to plan \(required if multiple causes exist\)"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from plan" -l "force" -d "Force new plan even if one exists"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from plan" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from plan" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from plan" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from view" -l "web" -d "Open in browser"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from view" -l "spans" -d "Span tree depth limit \(number, \"all\" for unlimited, \"no\" to disable\)"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from view" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from view" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from issue; and __fish_seen_subcommand_from view" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"

# event subcommands
complete -c sentry -n "__fish_seen_subcommand_from event" -a "view" -d "View details of a specific event"
complete -c sentry -n "__fish_seen_subcommand_from event; and __fish_seen_subcommand_from view" -l "web" -d "Open in browser"
complete -c sentry -n "__fish_seen_subcommand_from event; and __fish_seen_subcommand_from view" -l "spans" -d "Span tree depth limit \(number, \"all\" for unlimited, \"no\" to disable\)"
complete -c sentry -n "__fish_seen_subcommand_from event; and __fish_seen_subcommand_from view" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from event; and __fish_seen_subcommand_from view" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from event; and __fish_seen_subcommand_from view" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"

# log subcommands
complete -c sentry -n "__fish_seen_subcommand_from log" -a "list" -d "List logs from a project"
complete -c sentry -n "__fish_seen_subcommand_from log" -a "view" -d "View details of one or more log entries"
complete -c sentry -n "__fish_seen_subcommand_from log; and __fish_seen_subcommand_from list" -l "limit" -d "Number of log entries \(1-1000\)"
complete -c sentry -n "__fish_seen_subcommand_from log; and __fish_seen_subcommand_from list" -l "query" -d "Filter query \(Sentry search syntax\)"
complete -c sentry -n "__fish_seen_subcommand_from log; and __fish_seen_subcommand_from list" -l "follow" -d "Stream logs \(optionally specify poll interval in seconds\)"
complete -c sentry -n "__fish_seen_subcommand_from log; and __fish_seen_subcommand_from list" -l "period" -d "Time period \(e.g., \"30d\", \"14d\", \"24h\"\). Default: 30d \(project mode\), 14d \(trace mode\)"
complete -c sentry -n "__fish_seen_subcommand_from log; and __fish_seen_subcommand_from list" -l "sort" -d "Sort order: \"newest\" \(default\) or \"oldest\""
complete -c sentry -n "__fish_seen_subcommand_from log; and __fish_seen_subcommand_from list" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from log; and __fish_seen_subcommand_from list" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from log; and __fish_seen_subcommand_from list" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\). Available: sentry.item_id, timestamp, timestamp_precise, message, severity, trace"
complete -c sentry -n "__fish_seen_subcommand_from log; and __fish_seen_subcommand_from view" -l "web" -d "Open in browser"
complete -c sentry -n "__fish_seen_subcommand_from log; and __fish_seen_subcommand_from view" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from log; and __fish_seen_subcommand_from view" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from log; and __fish_seen_subcommand_from view" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"

# sourcemap subcommands
complete -c sentry -n "__fish_seen_subcommand_from sourcemap" -a "inject" -d "Inject debug IDs into JavaScript files and sourcemaps"
complete -c sentry -n "__fish_seen_subcommand_from sourcemap" -a "upload" -d "Upload sourcemaps to Sentry"
complete -c sentry -n "__fish_seen_subcommand_from sourcemap; and __fish_seen_subcommand_from inject" -l "ext" -d "Comma-separated file extensions to process \(default: .js,.cjs,.mjs\)"
complete -c sentry -n "__fish_seen_subcommand_from sourcemap; and __fish_seen_subcommand_from inject" -l "dry-run" -d "Show what would be modified without writing"
complete -c sentry -n "__fish_seen_subcommand_from sourcemap; and __fish_seen_subcommand_from inject" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from sourcemap; and __fish_seen_subcommand_from inject" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from sourcemap; and __fish_seen_subcommand_from upload" -l "release" -d "Release version to associate with the upload"
complete -c sentry -n "__fish_seen_subcommand_from sourcemap; and __fish_seen_subcommand_from upload" -l "url-prefix" -d "URL prefix for uploaded files \(default: ~/\)"
complete -c sentry -n "__fish_seen_subcommand_from sourcemap; and __fish_seen_subcommand_from upload" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from sourcemap; and __fish_seen_subcommand_from upload" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"

# span subcommands
complete -c sentry -n "__fish_seen_subcommand_from span" -a "list" -d "List spans in a project or trace"
complete -c sentry -n "__fish_seen_subcommand_from span" -a "view" -d "View details of specific spans"
complete -c sentry -n "__fish_seen_subcommand_from span; and __fish_seen_subcommand_from list" -l "limit" -d "Number of spans \(<=1000\)"
complete -c sentry -n "__fish_seen_subcommand_from span; and __fish_seen_subcommand_from list" -l "query" -d "Filter spans \(e.g., \"op:db\", \"duration:>100ms\", \"project:backend\"\)"
complete -c sentry -n "__fish_seen_subcommand_from span; and __fish_seen_subcommand_from list" -l "sort" -d "Sort order: date, duration"
complete -c sentry -n "__fish_seen_subcommand_from span; and __fish_seen_subcommand_from list" -l "period" -d "Time period \(e.g., \"1h\", \"24h\", \"7d\", \"30d\"\)"
complete -c sentry -n "__fish_seen_subcommand_from span; and __fish_seen_subcommand_from list" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from span; and __fish_seen_subcommand_from list" -l "cursor" -d "Navigate pages: \"next\", \"prev\", \"first\" \(or raw cursor string\)"
complete -c sentry -n "__fish_seen_subcommand_from span; and __fish_seen_subcommand_from list" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from span; and __fish_seen_subcommand_from list" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\). Available: id, parent_span, span.op, description, span.duration, timestamp, project, transaction, trace"
complete -c sentry -n "__fish_seen_subcommand_from span; and __fish_seen_subcommand_from view" -l "spans" -d "Span tree depth limit \(number, \"all\" for unlimited, \"no\" to disable\)"
complete -c sentry -n "__fish_seen_subcommand_from span; and __fish_seen_subcommand_from view" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from span; and __fish_seen_subcommand_from view" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from span; and __fish_seen_subcommand_from view" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"

# trace subcommands
complete -c sentry -n "__fish_seen_subcommand_from trace" -a "list" -d "List recent traces in a project"
complete -c sentry -n "__fish_seen_subcommand_from trace" -a "view" -d "View details of a specific trace"
complete -c sentry -n "__fish_seen_subcommand_from trace" -a "logs" -d "View logs associated with a trace"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from list" -l "limit" -d "Number of traces \(1-1000\)"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from list" -l "query" -d "Search query \(Sentry search syntax\)"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from list" -l "sort" -d "Sort by: date, duration"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from list" -l "period" -d "Time period \(e.g., \"1h\", \"24h\", \"7d\", \"30d\"\)"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from list" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from list" -l "cursor" -d "Navigate pages: \"next\", \"prev\", \"first\" \(or raw cursor string\)"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from list" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from list" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\). Available: trace, id, transaction, timestamp, transaction.duration, project"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from view" -l "web" -d "Open in browser"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from view" -l "spans" -d "Span tree depth limit \(number, \"all\" for unlimited, \"no\" to disable\)"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from view" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from view" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from view" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from logs" -l "web" -d "Open trace in browser"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from logs" -l "period" -d "Time period to search \(e.g., \"14d\", \"7d\", \"24h\"\). Default: 14d"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from logs" -l "limit" -d "Number of log entries \(<=1000\)"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from logs" -l "query" -d "Additional filter query \(Sentry search syntax\)"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from logs" -l "sort" -d "Sort order: \"newest\" \(default\) or \"oldest\""
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from logs" -l "fresh" -d "Bypass cache, re-detect projects, and fetch fresh data"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from logs" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from trace; and __fish_seen_subcommand_from logs" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"

# trial subcommands
complete -c sentry -n "__fish_seen_subcommand_from trial" -a "list" -d "List product trials"
complete -c sentry -n "__fish_seen_subcommand_from trial" -a "start" -d "Start a product trial"
complete -c sentry -n "__fish_seen_subcommand_from trial; and __fish_seen_subcommand_from list" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from trial; and __fish_seen_subcommand_from list" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\). Available: category, startDate, endDate, reasonCode, isStarted, lengthDays"
complete -c sentry -n "__fish_seen_subcommand_from trial; and __fish_seen_subcommand_from start" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from trial; and __fish_seen_subcommand_from start" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"

# help flags
complete -c sentry -n "__fish_seen_subcommand_from help" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from help" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"

# init flags
complete -c sentry -n "__fish_seen_subcommand_from init" -l "yes" -d "Non-interactive mode \(accept defaults\)"
complete -c sentry -n "__fish_seen_subcommand_from init" -l "dry-run" -d "Preview changes without applying them"
complete -c sentry -n "__fish_seen_subcommand_from init" -l "features" -d "Features to enable: errors,tracing,logs,replay,metrics,profiling,sourcemaps,crons,ai-monitoring,user-feedback"
complete -c sentry -n "__fish_seen_subcommand_from init" -l "team" -d "Team slug to create the project under"

# api flags
complete -c sentry -n "__fish_seen_subcommand_from api" -l "method" -d "The HTTP method for the request"
complete -c sentry -n "__fish_seen_subcommand_from api" -l "data" -d "Inline JSON body for the request \(like curl -d\)"
complete -c sentry -n "__fish_seen_subcommand_from api" -l "field" -d "Add a typed parameter \(key=value, key[sub]=value, key[]=value\)"
complete -c sentry -n "__fish_seen_subcommand_from api" -l "raw-field" -d "Add a string parameter without JSON parsing"
complete -c sentry -n "__fish_seen_subcommand_from api" -l "header" -d "Add a HTTP request header in key:value format"
complete -c sentry -n "__fish_seen_subcommand_from api" -l "input" -d "The file to use as body for the HTTP request \(use \"-\" to read from standard input\)"
complete -c sentry -n "__fish_seen_subcommand_from api" -l "silent" -d "Do not print the response body"
complete -c sentry -n "__fish_seen_subcommand_from api" -l "verbose" -d "Include full HTTP request and response in the output"
complete -c sentry -n "__fish_seen_subcommand_from api" -l "dry-run" -d "Show the resolved request without sending it"
complete -c sentry -n "__fish_seen_subcommand_from api" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from api" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"

# schema flags
complete -c sentry -n "__fish_seen_subcommand_from schema" -l "all" -d "Show all endpoints in a flat list"
complete -c sentry -n "__fish_seen_subcommand_from schema" -l "search" -d "Search endpoints by keyword"
complete -c sentry -n "__fish_seen_subcommand_from schema" -l "json" -d "Output as JSON"
complete -c sentry -n "__fish_seen_subcommand_from schema" -l "fields" -d "Comma-separated fields to include in JSON output \(dot.notation supported\)"

# Dynamic completions (org slugs, project names)
complete -c sentry -n "not __fish_use_subcommand" -a "" -k
complete -c sentry -a "(__sentry_complete_dynamic)"
